"""Literal design-golden and pure negative evidence. No native or Project I/O."""
from dataclasses import replace
from hashlib import sha256
import math
import struct
import threading

import pytest

from ai_video_production import task048_meter_protocol as p

# Independent design 99913B95... literal bytes; not generated by the implementation.
GOLDEN = {
    "BOOTSTRAP": (186, "0b7ec9a406d8f037817b15cb09727dce97fa986d0746411a828af2fb7a98c982",
        "b600000042564d31010001000100000000000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f000000000000400080000000000000060100000000000000111111111111111111111111111111110400000000000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0d0025006d657465722d70726f6a656374433a5c55736572735c6578616d706c655c446f63756d656e74735c63312d70726f6a656374"),
    "WINDOW": (197, "d0a487a835800ee4e46a5e12151a9fbb7b71f7cb15031035e23782a1882a9a21",
        "c100000042564d31010002000200000000000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f000000000000400080000000000000060000000000004000800000000000000100000000000040008000000000000002000000000000400080000000000000070100000000000000010000000001000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000032c00000000000000032c00000000000000032c0"),
    "INVALIDATE": (120, "54faa59d734159f75f1873922e6c0087d24a0fc93e748a640b92a606a594b165",
        "7400000042564d31010004000300000000000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f0000000000004000800000000000000600000000000040008000000000000001000000000000400080000000000000080000000000004000800000000000000904010000"),
    "CLOSE": (72, "5929b9d7c39d7f37c7aa39e3e12d54ab70989fa31681ced0902fa657cf2ddca3",
        "4400000042564d31010005000400000000000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f0000000000004000800000000000000601000000"),
    "RESULT_READY": (208, "b19f2a87777de9aa22eda6f40d6384bc3ac1908694fb705fe977e8a385969b85",
        "cc00000042564d31010003000100000000000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f0000010001000000000000000b7ec9a406d8f037817b15cb09727dce97fa986d0746411a828af2fb7a98c982000000000000400080000000000000060400000000000000aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0100000000000000111111111111111111111111111111110000000000004000800000000000000400000000000040008000000000000005"),
    "RESULT_STATUS": (112, "8ad4e11ea9d42886198dcb5addf8ecddb27552f8ae38fa1d1998a9f7cd02a05e",
        "6c00000042564d31010003000300000000000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f02080400030000000000000054faa59d734159f75f1873922e6c0087d24a0fc93e748a640b92a606a594b16500000000000040008000000000000006"),
    "RESULT_PROJECTION": (3822, "16295d65b8b56d97ce55f15f39de0d7c0764f4b20661463d8c2a0c8b33672a8a",
        "ea0e000042564d31010003000200000000000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f010002000200000000000000d0a487a835800ee4e46a5e12151a9fbb7b71f7cb15031035e23782a1882a9a2100000000000040008000000000000006000000000000400080000000000000010000000000004000800000000000000200000000000040008000000000000007010000000000000001000000000000000000000000004000800000000000000300000000000040008000000000000004000000000000400080000000000000050988969cd5eb0982ce6c21b9cf05d63d5bda92dafb8f161d7774a29bcd533730bfb0abc58ea59ef4821df2113b9a5c9d913765663df7e001deb1c399a72e506e02290e0a58ef1b031955286138c72626c3084c8ffd7df8b59b9a5e9b4548ba6502110000860d0000dcf406d1bd2506683add92eb3df1e93b8c686fe584ccf8dbcb8f338e0d02ad9d7b22617574686f72697479223a7b22617574686f726974795f63726561746564223a66616c73652c22636170747572655f617574686f72697a6564223a66616c73652c22636170747572655f706174685f6e6f6e696e746572666572656e63655f636f6e6669726d6564223a66616c73652c22636f6e73656e745f61737365745f747261696e696e675f6d6f64656c5f617574686f72697a6564223a66616c73652c22656d657267656e63795f73746f705f6e6f6e696e746572666572656e63655f636f6e6669726d6564223a66616c73652c226761696e5f6368616e67655f617574686f72697a6564223a66616c73652c2268617264776172655f6f725f6f62735f73657474696e675f6368616e676564223a66616c73652c2270726f64756374696f6e5f617574686f72697a6564223a66616c73652c2270726f76696465725f696e766f6b6564223a66616c73652c227175616c6974795f706173735f697373756564223a66616c73652c2274656d706f72616c5f66726573686e6573735f636f6e6669726d6564223a66616c73657d2c2263616e6f6e6963616c5f6f776e65725f7461736b223a225441534b2d303438222c22646973706c61795f62616e64223a22544152474554222c22696f5f626f756e64617279223a7b22617564696f5f73656d616e7469635f6465636f64655f6578656375746564223a66616c73652c22617564696f5f757365645f61735f706f6c6963795f696e707574223a66616c73652c22636170747572655f7472616e73706f72745f6170695f696e766f6b6564223a66616c73652c22656d657267656e63795f73746f705f6170695f696e766f6b6564223a66616c73652c22706f6c6963795f6f725f70726f6a6563745f77726974655f6578656375746564223a66616c73652c2270726f6a6563745f696e746567726974795f686173685f72656164735f706f737369626c65223a747275657d2c226c6976655f61646d697373696f6e5f73657269616c697a6564223a66616c73652c226f62736572766174696f6e223a7b2263616e6f6e6963616c5f6f776e65725f7461736b223a225441534b2d303438222c22636170747572655f706f696e74223a225441534b3034375f434f4e54524f4c4c45525f52454345495645445f464c4f415433325f5052455f44524157222c226f62736572766174696f6e5f736861323536223a227368613235363a30393838393639636435656230393832636536633231623963663035643633643562646139326461666238663136316437373734613239626364353333373330222c22706175736564223a66616c73652c2271756572795f636f6e74657874223a7b22636f6e73756d65725f65706f6368223a2230303030303030302d303030302d343030302d383030302d303030303030303030303032222c2270726f6a6563745f6964223a226d657465722d70726f6a656374222c22726571756573745f6964223a2230303030303030302d303030302d343030302d383030302d303030303030303030303033222c2273657373696f6e5f6964223a2230303030303030302d303030302d343030302d383030302d303030303030303030303031222c2277696e646f775f73657175656e6365223a317d2c227265636f72645f74797065223a225461736b3034384d6574657252756e74696d654f62736572766174696f6e5631222c22736368656d615f76657273696f6e223a312c2273657373696f6e5f636f756e7473223a7b22636c69705f73616d706c655f76616c756573223a302c2266696e6974655f73616d706c655f76616c756573223a312c227374617465223a2256414c4944227d2c2273657373696f6e5f7065616b223a7b227374617465223a2246494e495445222c2276616c75655f64626673223a2d31382e307d2c2277696e646f775f636f756e7473223a7b22636c69705f73616d706c655f76616c756573223a302c2266696e6974655f73616d706c655f76616c756573223a312c226e6f6e66696e6974655f73616d706c655f76616c756573223a302c227374617465223a2256414c4944227d2c2277696e646f775f6c6f73735f7374617465223a224e4f5f4c4f53535f5245504f52544544222c2277696e646f775f7065616b223a7b227374617465223a2246494e495445222c2276616c75655f64626673223a2d31382e307d2c2277696e646f775f726d73223a7b227374617465223a2246494e495445222c2276616c75655f64626673223a2d31382e307d7d2c226f62736572766174696f6e5f7374617465223a224d45415355524544222c226f70657261746f725f6c6162656c223a22e79baee6a899e7af84e59bb2222c22706f6c6963795f6f62736572766174696f6e223a7b226566666563746976655f737461747573223a2250524f4a4543545f484541445f4d4154434845445f534e415053484f54222c2266696e616c5f737461747573223a2250524f4a4543545f484541445f4d4154434845445f534e415053484f54222c226964656e74697479223a7b226368696c645f736861323536223a227368613235363a62626262626262626262626262626262626262626262626262626262626262626262626262626262626262626262626262626262626262626262626262626262222c2270726f64756365725f65706f6368223a2230303030303030302d303030302d343030302d383030302d303030303030303030303035222c2270726f6a6563745f6964223a226d657465722d70726f6a656374222c2270726f6a6563745f6d616e69666573745f736861323536223a227368613235363a61616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161616161222c2270726f6a6563745f7265766973696f6e223a342c2273656c65637465645f706f6c6963795f736861323536223a227368613235363a62623736323565303236623631383836376163663539313435306435363936656338323563646364303962383862393733383039633930343564376433396265222c2273746174655f7265766973696f6e223a337d2c22696e697469616c5f737461747573223a2250524f4a4543545f484541445f4d4154434845445f534e415053484f54222c22706f6c6963795f646f63756d656e74223a7b2263616e6f6e6963616c5f6f776e65725f7461736b223a225441534b2d303438222c22706f6c6963795f726566223a226d657465722d706f6c696379222c22706f6c6963795f7265766973696f6e223a312c22706f6c6963795f7265766973696f6e5f736861323536223a227368613235363a62623736323565303236623631383836376163663539313435306435363936656338323563646364303962383862393733383039633930343564376433396265222c227072656465636573736f725f706f6c6963795f736861323536223a6e756c6c2c227265636f72645f74797065223a225461736b3034384d65746572446973706c6179506f6c6963795265766973696f6e5631222c22736368656d615f76657273696f6e223a312c227461726765745f6365696c696e675f64626673223a2d31322e302c227461726765745f666c6f6f725f64626673223a2d32342e302c22747275655f636c69705f64626673223a302e302c227761726e696e675f64626673223a2d332e307d2c2277696e646f775f706f6c6963795f6d617463686564223a747275657d2c22706f6c6963795f70726f64756365725f65706f6368223a2230303030303030302d303030302d343030302d383030302d303030303030303030303035222c2270726f6a656374696f6e5f736861323536223a227368613235363a30323239306530613538656631623033313935353238363133386337323632366333303834633866666437646638623539623961356539623435343862613635222c2271756572795f636f6e74657874223a7b22636f6e73756d65725f65706f6368223a2230303030303030302d303030302d343030302d383030302d303030303030303030303032222c2270726f6a6563745f6964223a226d657465722d70726f6a656374222c22726571756573745f6964223a2230303030303030302d303030302d343030302d383030302d303030303030303030303033222c2273657373696f6e5f6964223a2230303030303030302d303030302d343030302d383030302d303030303030303030303031222c2277696e646f775f73657175656e6365223a317d2c22726561736f6e5f636f6465223a2257494e444f575f504f4c4943595f434c4153534946494544222c227265636f72645f74797065223a225461736b3034384d6574657252756e74696d654465636973696f6e50726f6a656374696f6e5631222c22726571756573745f736861323536223a227368613235363a62666230616263353865613539656634383231646632313133623961356339643931333736353636336466376530303164656231633339396137326535303665222c2272756e74696d655f65706f6368223a2230303030303030302d303030302d343030302d383030302d303030303030303030303034222c22736368656d615f76657273696f6e223a312c2273636f70655f6c6162656c223a22e4bb8ae59b9ee381aee8a6b3e6b8ace7aa93e381abe5afbee38199e3828be696b9e9879de785a7e59088222c2277696e646f775f6f6e6c79223a747275657d"),
}

def message(name="WINDOW"):
    return p.decode_message(bytes.fromhex(GOLDEN[name][2]))


def window():
    return message().body


def uid(n):
    return f"00000000-0000-4000-8000-{n:012x}"


def wire(body, sequence=2):
    return p.encode_message(body, nonce=bytes(range(32)), sequence=sequence)


def changed(raw, offset, value):
    out = bytearray(raw)
    out[offset:offset+len(value)] = value
    return bytes(out)


@pytest.mark.parametrize("name", GOLDEN)
def test_seven_literal_design_vectors(name):
    length, digest, literal = GOLDEN[name]
    data = bytes.fromhex(literal)
    assert len(data) == length
    assert sha256(data).hexdigest() == digest
    result = p.decode_message(data)
    assert p.encode_message(result.body, nonce=result.nonce, sequence=result.sequence) == data
    assert result.sha256.hex() == digest


@pytest.mark.parametrize("bad", [None, "", bytearray(b"a"), memoryview(b"a"), 1, True, {}, []])
def test_exact_bytes_only(bad):
    with pytest.raises(p.ProtocolError):
        p.decode_message(bad)


@pytest.mark.parametrize("name", GOLDEN)
@pytest.mark.parametrize("mode", ["short", "extra", "size_minus", "size_plus", "magic", "version", "type", "nonce", "sequence"])
def test_malformed_frame_rejected(name, mode):
    raw = bytes.fromhex(GOLDEN[name][2])
    if mode == "short":
        bad = raw[:-1]
    elif mode == "extra":
        bad = raw + b"\0"
    elif mode.startswith("size"):
        size = int.from_bytes(raw[:4], "little") + (1 if mode.endswith("plus") else -1)
        bad = changed(raw, 0, struct.pack("<I", size))
    elif mode == "magic":
        bad = changed(raw, 4, b"FAIL")
    elif mode == "version":
        bad = changed(raw, 8, b"\2\0")
    elif mode == "type":
        bad = changed(raw, 10, b"\xff\xff")
    elif mode == "nonce":
        bad = changed(raw, 20, b"\0" * 32)
    else:
        bad = changed(raw, 12, b"\0" * 8)
    with pytest.raises(p.ProtocolError):
        p.decode_message(bad)


@pytest.mark.parametrize("offset", [72, 73, 74, 75, 76, 101, 118, 127, 136])
def test_window_closed_enums_and_reserved(offset):
    with pytest.raises(p.ProtocolError):
        p.decode_message(changed(message().wire, 52+offset, b"\xff"))


@pytest.mark.parametrize("value", [math.inf, -math.inf, math.nan])
@pytest.mark.parametrize("offset", [119, 128, 137])
def test_nonfinite_metric_bits_refused(value, offset):
    with pytest.raises(p.ProtocolError):
        p.decode_message(changed(message().wire, 52+offset, struct.pack("<d", value)))


@pytest.mark.parametrize("value", [-0.0, 0.1, 6.0, 12.0, 18.0, float.fromhex("0x1.fffffffffffffp+1023")])
def test_finite_binary64_bits_preserved(value):
    metric = p.Metric(p.MetricState.FINITE, value)
    result = p.decode_message(wire(replace(window(), window_peak=metric))).body.window_peak
    assert struct.pack("<d", result.value_dbfs) == struct.pack("<d", value)


@pytest.mark.parametrize("state", list(p.MetricState)[1:])
def test_null_metric_reserved_zero_and_negative_zero_rejection(state):
    body = replace(window(), window_peak=p.Metric(state, None))
    raw = wire(body)
    assert p.decode_message(raw).body.window_peak.value_dbfs is None
    with pytest.raises(p.ProtocolError):
        p.decode_message(changed(raw, 52+119, struct.pack("<d", -0.0)))


@pytest.mark.parametrize("state", [p.CountState.COUNTER_OVERFLOW, p.CountState.UNAVAILABLE])
def test_unavailable_counts_are_null_not_measured_zero(state):
    body = replace(window(), window_counts=p.WindowCounts(state, None, None, None),
                   session_counts=p.SessionCounts(state, None, None))
    result = p.decode_message(wire(body)).body
    assert result.window_counts.finite is None
    assert result.session_counts.clips is None
    with pytest.raises(p.ProtocolError):
        p.decode_message(changed(wire(body), 52+77, struct.pack("<Q", 1)))


@pytest.mark.parametrize("count", [-1, True, 1.0, p.MAX_INTEGER+1])
def test_counts_require_bounded_exact_integer(count):
    body = replace(window(), window_counts=p.WindowCounts(p.CountState.VALID, count, 0, 0))
    with pytest.raises(p.ProtocolError):
        wire(body)


def test_clips_cannot_exceed_finite_count():
    body = replace(window(), window_counts=p.WindowCounts(p.CountState.VALID, 1, 0, 2))
    with pytest.raises(p.ProtocolError):
        wire(body)


@pytest.mark.parametrize("root", ["C:\\", "C:\\project", "c:\\Users\\example", "\\\\server\\share\\project",
                                "C:\\Users\\..\\project", "C:\\Users\\project\\", "C:\\Users\\project:ads",
                                "C:\\Users\\bad.", "C:\\Users\\bad\x00name", "C:/Users/example"])
def test_bootstrap_path_syntax_is_fail_closed_without_io(root):
    body = replace(message("BOOTSTRAP").body, project_root=root)
    with pytest.raises(p.ProtocolError):
        p.encode_message(body, nonce=bytes(range(32)), sequence=1)


def test_private_bootstrap_and_message_repr_do_not_disclose_path():
    body = message("BOOTSTRAP").body
    assert body.project_root not in repr(body)
    assert body.project_root not in repr(message("BOOTSTRAP"))


@pytest.mark.parametrize("name,offset", [("WINDOW", 52), ("BOOTSTRAP", 52),
                                       ("RESULT_READY", 52+124), ("INVALIDATE", 52+16)])
def test_mixed_endian_uuid_is_not_rfc_uuid4(name, offset):
    raw = bytes.fromhex(GOLDEN[name][2])
    little_guid = bytes.fromhex("00000000000000408000000000000006")
    with pytest.raises(p.ProtocolError):
        p.decode_message(changed(raw, offset, little_guid))


@pytest.mark.parametrize("offset", [52+268, 52+269, 52+270])
def test_projection_closed_codes(offset):
    with pytest.raises(p.ProtocolError):
        p.decode_message(changed(message("RESULT_PROJECTION").wire, offset, b"\xff"))


def test_projection_hash_length_and_utf8_refusal():
    raw = message("RESULT_PROJECTION").wire
    for offset in (52+272, 52+276, len(raw)-1):
        with pytest.raises(p.ProtocolError):
            p.decode_message(changed(raw, offset, bytes((raw[offset] ^ 1,))))


@pytest.mark.parametrize("proof", [b'\xef\xbb\xbf{}', b'{"a":"\x00"}'])
def test_rehashed_proof_with_bom_or_nul_is_not_admitted(proof):
    raw = bytearray(message("RESULT_PROJECTION").wire[:52+308])
    raw[52+272:52+276] = len(proof).to_bytes(4, "little")
    raw[52+276:52+308] = sha256(proof).digest()
    raw += proof
    raw[:4] = (len(raw)-4).to_bytes(4, "little")
    with pytest.raises(p.ProtocolError):
        p.decode_message(bytes(raw))


def test_native_v1_cannot_promote_unknown_loss():
    for loss in p.Loss:
        observed = p.native_v1_observation(replace(window(), loss=loss))
        assert observed.loss is p.Loss.UNKNOWN
        assert observed.capture_point is p.CapturePoint.CONTROLLER_FLOAT32_PRE_DRAW


def test_response_correlation_binds_exact_wire():
    original = message()
    correlation = p.response_correlation(original)
    assert correlation.source_sha256 == original.sha256
    with pytest.raises(p.ProtocolError):
        p.response_correlation(replace(original, sequence=4))


def test_ordered_receiver_rejects_replay_skip_wrong_nonce_and_direction():
    for bad in [message().wire, wire(window(), sequence=3),
                p.encode_message(window(), nonce=b"x"*32, sequence=2),
                message("RESULT_READY").wire]:
        receiver = p.OrderedReceiver(allowed=(p.MessageType.BOOTSTRAP, p.MessageType.WINDOW))
        receiver.accept(message("BOOTSTRAP").wire)
        if bad == message().wire:
            receiver.accept(bad)
        with pytest.raises(p.ProtocolError):
            receiver.accept(bad)
        assert receiver.closed
        with pytest.raises(p.ProtocolError):
            receiver.accept(message().wire)


def test_accumulator_fragmentation_and_coalescing():
    chunks = message("BOOTSTRAP").wire + message().wire
    reader = p.FrameAccumulator()
    results = []
    for i, value in enumerate(chunks):
        results.extend(reader.feed(bytes((value,)), now_ns=i))
    assert [x.kind for x in results] == [p.MessageType.BOOTSTRAP, p.MessageType.WINDOW]
    assert p.FrameAccumulator().feed(chunks, now_ns=0) == tuple(results)


def test_accumulator_huge_prefix_timeout_eof_no_resync():
    reader = p.FrameAccumulator()
    with pytest.raises(p.ProtocolError):
        reader.feed(struct.pack("<I", 65533), now_ns=0)
    with pytest.raises(p.ProtocolError):
        reader.feed(message().wire, now_ns=0)
    reader = p.FrameAccumulator()
    reader.feed(b"\xc1", now_ns=0)
    reader.expire(999_999_999)
    with pytest.raises(p.ProtocolError):
        reader.expire(1_000_000_000)
    reader = p.FrameAccumulator()
    reader.feed(b"\xc1", now_ns=0)
    reader.eof()
    with pytest.raises(p.ProtocolError):
        reader.feed(message().wire, now_ns=1)


@pytest.mark.parametrize("elapsed,accepted", [(249_000_000, True), (250_000_000, False), (251_000_000, False)])
def test_monotonic_249_250_251_display_boundary(elapsed, accepted):
    scheduler = p.LatestWindowScheduler()
    scheduler.offer(window(), now_ns=0)
    job = scheduler.take()
    assert scheduler.finish(job, message("RESULT_PROJECTION").body, now_ns=elapsed) is accepted
    assert (scheduler.display(now_ns=elapsed) is not None) is accepted
    assert scheduler.display(now_ns=250_000_000) is None


def test_latest_one_stale_clear_and_owned_active_slot():
    scheduler = p.LatestWindowScheduler()
    scheduler.offer(window(), now_ns=0)
    old = scheduler.take()
    for seq in range(2, 101):
        scheduler.offer(replace(window(), ui_sequence=seq), now_ns=seq)
        assert scheduler.occupancy == (1, 1)
        assert scheduler.take() is None
    with pytest.raises(p.ProtocolError):
        scheduler.finish(replace(old), None, now_ns=101)
    assert scheduler.occupancy == (1, 1)
    assert not scheduler.finish(old, message("RESULT_PROJECTION").body, now_ns=102)
    assert scheduler.display(now_ns=102) is None
    latest = scheduler.take()
    assert latest.window.ui_sequence == 100


@pytest.mark.parametrize("action", ["invalidate", "close", "new_window"])
def test_invalidation_keeps_lease_slot_until_exact_job_drains(action):
    scheduler = p.LatestWindowScheduler()
    scheduler.offer(window(), now_ns=0)
    job = scheduler.take()
    if action == "new_window":
        scheduler.offer(replace(window(), ui_sequence=2), now_ns=1)
    else:
        getattr(scheduler, action)()
    assert scheduler.occupancy[0] == 1
    assert scheduler.take() is None
    assert not scheduler.finish(job, message("RESULT_PROJECTION").body, now_ns=2)
    assert scheduler.occupancy[0] == 0
    assert scheduler.display(now_ns=2) is None


def test_scheduler_concurrent_offer_is_bounded_and_does_not_run_user_callbacks():
    scheduler = p.LatestWindowScheduler()
    scheduler.offer(window(), now_ns=0)
    active = scheduler.take()
    errors = []
    def producer():
        try:
            for seq in range(2, 1000):
                scheduler.offer(replace(window(), ui_sequence=seq), now_ns=seq)
        except Exception as error:
            errors.append(type(error))
    thread = threading.Thread(target=producer)
    thread.start()
    thread.join(2)
    assert not thread.is_alive() and not errors
    assert scheduler.occupancy == (1, 1)
    scheduler.finish(active, None, now_ns=1000)
    assert scheduler.take().window.ui_sequence == 999
